Repository uyuni-project/uyuni-tools, pull requests merged in 2025-07, with the labels that each got.

#630 Do not use /var/lib/pgsql/data-backup for database backup (bsc#1246628)
  mgradm/shared/podman/podman.go
  mgradm/shared/templates/pgsqlVersionUpgradeScriptTemplate.go
  mgradm/shared/utils/exec.go
  uyuni-tools.changes.oholecek.fix_database_backup_location
Labels: ga-blocker

#631 Upgrade saline should use scale function
  mgradm/shared/saline/saline.go
  uyuni-tools.changes.mbussolotto.upgrade_saline
Labels: merge-candidate, wait-branch-unlock:master

#619 support config: collect podman inspect for hub container
  mgradm/cmd/support/config/extractor.go
  mgradm/shared/templates/salineServiceTemplate.go
  shared/podman/support.go
  shared/utils/support.go
  uyuni-tools.changes.mbussolotto.config_hub
Labels: merge-candidate

#585 Fix mgradm start / stop to work with 5.0 for upgrade
  check_localizable
  mgradm/cmd/backup/create/systemd_utils.go
  mgradm/cmd/backup/restore/restore.go
  mgradm/cmd/install/podman/utils.go
  mgradm/cmd/migrate/podman/utils.go
  mgradm/cmd/restart/podman.go
  mgradm/cmd/scale/podman.go
  mgradm/cmd/status/podman.go
  mgradm/cmd/support/config/extractor.go
  mgradm/cmd/support/ptf/podman/utils.go
  mgradm/cmd/uninstall/podman.go
  mgradm/cmd/upgrade/podman/utils.go
  mgradm/shared/podman/podman.go
  mgradm/shared/podman/startstop.go
  mgradm/shared/podman/startstop_test.go
  mgradm/shared/utils/flags.go
  mgrpxy/cmd/cache/podman.go
  mgrpxy/cmd/install/podman/utils.go
  mgrpxy/cmd/logs/logs.go
  mgrpxy/cmd/restart/podman.go
  mgrpxy/cmd/start/podman.go
  mgrpxy/cmd/status/status.go
  mgrpxy/cmd/stop/podman.go
  mgrpxy/cmd/support/config/extractor.go
  mgrpxy/cmd/support/ptf/podman/utils.go
  mgrpxy/cmd/uninstall/podman.go
  mgrpxy/cmd/upgrade/podman/utils.go
  shared/connection.go
  shared/podman/interfaces.go
  shared/podman/support.go
  shared/podman/systemd.go
  shared/podman/systemd_test.go
  shared/testutils/asserts.go
  shared/testutils/systemd.go
  uyuni-tools.changes.cbosdo.stop-fix
Labels: merge-candidate
